bucket_name = "your_bucket"
aopcs_path = "resources/aopcs/kineis"
secret_manager_arn = "arn:yours"

[lambda_configuration]
    duration = 30
    memory = 256
    [lambda_configuration.environment_variables]
        LOG_LEVEL = "DEBUG"
        bucket_name = "your_bucket"
        aopcs_path = "resources/aopcs/kineis"
        secret_manager_arn = "arn:yours"
