bucket_name = "atlas-resources-bucket-validation"
aopcs_path = "resources/aopcs/kineis"
secret_manager_arn = "arn:aws:secretsmanager:eu-west-3:182399725777:secret:aopcs/kineis/api-6wU7OV"

[lambda_configuration]
    duration = 30
    memory = 256
    eventbridge_hour = 6
    eventbridge_minute = 10
    [lambda_configuration.environment_variables]
        LOG_LEVEL = "DEBUG"
        bucket_name = "atlas-resources-bucket-validation"
        aopcs_path = "resources/aopcs/kineis"
        secret_manager_arn = "arn:aws:secretsmanager:eu-west-3:182399725777:secret:aopcs/kineis/api-6wU7OV"
